Bricks.cpp

void BRICK()
{
  int num,top,bot,mun,col;
  bot=30;top=10;num=10;mun=30;
  randomize();
  for(int j=1;j<=25;j++)
  {
     setfillstyle(SOLID_FILL,4);
     delay(1);
     bar(num,top,mun,bot);
     num=mun+5;
     mun=random(60)+num;
  }
  int num1,top1,bot1,mun1;
  bot1=60;top1=40;num1=10;mun1=50;
  randomize();
  for(int k=1;k<=25;k++)
  {
    setfillstyle(SOLID_FILL,6);
    delay(1);
    bar(num1,top1,mun1,bot1);
    num1=mun1+5;
    mun1=random(50)+num1;
  
  }
  int num2,top2,bot2,mun2;
  bot2=90;top2=70;num2=10;mun2=70;
  randomize();
  for(int l=1;l<=25;l++)
  {
    setfillstyle(SOLID_FILL,14);
    bar(num2,top2,mun2,bot2);
    delay(1);
    num2=mun2+5;
    mun2=random(50)+num2;
  }
  int num3,top3,bot3,mun3;
  bot3=120;top3=100;num3=10;mun3=40;
  randomize();
  for(int m=1;m<=25;m++)
  {
    setfillstyle(SOLID_FILL,2);
    delay(1);
    bar(num3,top3,mun3,bot3);
    num3=mun3+5;
    mun3=random(50)+num3;
  }
  int num4,top4,bot4,mun4;
  bot4=150;top4=130;num4=10;mun4=26;
  randomize();
  for(int n=1;n<=25;n++)
  {
    setfillstyle(SOLID_FILL,1);
    delay(1);
    bar(num4,top4,mun4,bot4);
    num4=mun4+5;
    mun4=random(50)+num4;
  }
  int num5,top5,bot5,mun5;
  bot5=180;top5=160;num5=10;mun5=56;
  randomize();
  for(int o=1;o<=25;o++)
  {
    setfillstyle(SOLID_FILL,3);
    delay(1);
    bar(num5,top5,mun5,bot5);
    num5=mun5+5;
    mun5=random(50)+num5;
  }
  int num6,top6,bot6,mun6;
  bot6=210;top6=190;num6=10;mun6=36;
  randomize();
  for(int p=1;p<=25;p++)
  {
    setfillstyle(SOLID_FILL,7);
    delay(1);
    bar(num6,top6,mun6,bot6);
    num6=mun6+5;
    mun6=random(50)+num6;
  }
  int num7,top7,bot7,mun7;
  bot7=240;top7=220;num7=10;mun7=46;
  randomize();
  for(int q=1;q<=25;q++)
  {
    setfillstyle(SOLID_FILL,8);
    delay(1);
    bar(num7,top7,mun7,bot7);
    num7=mun7+5;
    mun7=random(50)+num7;
  }
  int num8,top8,bot8,mun8;
  bot8=270;top8=250;num8=10;mun8=76;
  randomize();
  for(int r=1;r<=25;r++)
  {
    setfillstyle(SOLID_FILL,10);
    delay(1);
    bar(num8,top8,mun8,bot8);
    num8=mun8+5;
    mun8=random(50)+num8;
  }
  int num9,top9,bot9,mun9;
  bot9=300;top9=280;num9=10;mun9=86;
  randomize();
  for(int s=1;s<=25;s++)
  {
    setfillstyle(SOLID_FILL,11);
    delay(1);
    bar(num9,top9,mun9,bot9);
    num9=mun9+5;
    mun9=random(50)+num9;
  }
  int num10,top10,bot10,mun10;
  bot10=330;top10=310;num10=10;mun10=96;
  randomize();
  for(int t=1;t<=25;t++)
  {
    setfillstyle(SOLID_FILL,7);
    delay(1);
    bar(num10,top10,mun10,bot10);
    num10=mun10+5;
    mun10=random(50)+num10;
  }
  int num11,top11,bot11,mun11;
  bot11=360;top11=340;num11=10;mun11=106;
  randomize();
  for(int u=1;u<=25;u++)
  {
    setfillstyle(SOLID_FILL,8);
    delay(1);
    bar(num11,top11,mun11,bot11);
    num11=mun11+5;
    mun11=random(50)+num11;
  }   
  int num12,top12,bot12,mun12;
  bot12=390;top12=370;num12=10;mun12=116;
  randomize();
  for(int v=1;v<=25;v++)
  {
    setfillstyle(SOLID_FILL,14);
    delay(1);
    bar(num12,top12,mun12,bot12);
    num12=mun12+5;
    mun12=random(50)+num12;
  }
  int num13,top13,bot13,mun13;
  bot13=420;top13=400;num13=10;mun13=126;
  randomize();
  for(int w=1;w<=25;w++)
  {
    setfillstyle(SOLID_FILL,17);
    delay(1);
    bar(num13,top13,mun13,bot13);
    num13=mun13+5;
    mun13=random(50)+num13;
  }
  int num14,top14,bot14,mun14;
  bot14=450;top14=430;num14=10;mun14=136;
  randomize();
  for(int x=1;x<=25;x++)
  {
    setfillstyle(SOLID_FILL,18);
    delay(1);
    bar(num14,top14,mun14,bot14);
    num14=mun14+5;
    mun14=random(50)+num14;
  }
  int num15,top15,bot15,mun15;
  bot15=480;top15=460;num15=10;mun15=16;
  randomize();
  for(int y=1;y<=25;y++)
  {
    setfillstyle(SOLID_FILL,3);
    delay(1);
    bar(num15,top15,mun15,bot15);
    num15=mun15+5;
    mun15=random(50)+num15;
  }
  int num16,top16,bot16,mun16;
  bot16=510;top16=490;num16=10;mun16=16;
  randomize();
  for(int z=1;z<=25;z++)
  {
    setfillstyle(SOLID_FILL,4);
    delay(1);
    bar(num16,top16,mun16,bot16);
    num16=mun16+5;
    mun16=random(50)+num16;
  }
  getch();
}